# Gradle
org.gradle.jvmargs=-Xmx8192m
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Project
project.name=Kotlin SQLite
project.group=io.github.manriif.ksqlite
project.website=https://github.com/manriif/ksqlite
project.license.name=Apache 2.0 License
project.license.url=https://github.com/manriif/ksqlite/blob/main/LICENSE
project.git.base=github.com/manriif/ksqlite
project.git.url=https://github.com/manriif/ksqlite
project.dev.id=manriif
project.dev.name=Maanrifa Bacar Ali
project.dev.url=https://github.com/manriif

# Checksums
# SQLite official source tree (SHA3-256) -> https://www.sqlite.org/download.html
checksum.sqlite=2daecfa16e3b19e058dc2e2cb717b80ade361e0315aa5376c3619f66aa81e181
# SQLite Multiple Ciphers (SHA-256) -> https://github.com/utelle/SQLite3MultipleCiphers/releases
checksum.sqlitemc=bbd0434f9456d810cd1bb8d3767985f18f6b84648f1cd9cd1db6ccfb01819da2