# Gradle
org.gradle.jvmargs=-Xmx8192m
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Project
project.namespace=ksqlite
project.name=Kotlin SQLite
project.group=io.github.manriif.ksqlite
project.website=https://github.com/manriif/ksqlite
project.license.name=Apache 2.0 License
project.license.url=https://github.com/manriif/ksqlite/blob/main/LICENSE
project.git.base=github.com/manriif/ksqlite
project.git.url=https://github.com/manriif/ksqlite
project.dev.id=manriif
project.dev.name=Maanrifa Bacar Ali
project.dev.url=https://github.com/manriif

# Checksums
# SQLite official source tree (SHA3-256) -> https://www.sqlite.org/download.html
checksum.sqlite=490ec7af32a6bfa5f3e05dc279c04286cfe3f328def4a8b7344e3fa20be18a4c
# SQLite Multiple Ciphers (SHA-256) -> https://github.com/utelle/SQLite3MultipleCiphers/releases
checksum.sqlitemc=4533dcdf82b9b0f00173067be2eee8fc42010f2678a1c1ed63434f7cedfbe5d3