# Gradle
org.gradle.jvmargs=-Xmx8192m
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Project
project.namespace=ksqlite
project.name=Kotlin SQLite
project.group=io.github.manriif.ksqlite
project.website=https://github.com/manriif/ksqlite
project.license.name=Apache 2.0 License
project.license.url=https://github.com/manriif/ksqlite/blob/main/LICENSE
project.git.base=github.com/manriif/ksqlite
project.git.url=https://github.com/manriif/ksqlite
project.dev.id=manriif
project.dev.name=Maanrifa Bacar Ali
project.dev.url=https://github.com/manriif

# Checksums
# SQLite official source tree (SHA3-256) -> https://www.sqlite.org/download.html
checksum.sqlite=e436bb919850445ce5168fb033d2d0d5c53a9d8c9602c7fa62b3e0025541d481
# SQLite Multiple Ciphers (SHA-256) -> https://github.com/utelle/SQLite3MultipleCiphers/releases
checksum.sqlitemc=8e84aadc53bc09bda9cd307745a178191e7783e1b6478d74ffbcdf6a04f98085