# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]

# Project version, matching the targeted sqlite version
ksqlite = "3.51.2"

# Toolchains
toolchain-android = "r29.14206865"
toolchain.zig = "0.15.2"

# Android
android-ndk = "29.0.14206865"
android-sdk-compile = "36"
android-sdk-min = "21"

# Apple
macos-version-min = "10.13"
ios-version-min = "12.0"
tvos-version-min = "12.0"
watchos-version-min = "5.0"

# Jvm versions
jvm-target-android = "17"
jvm-target-jvm = "22"
jvm-toolchain = "22"

android-gradlePlugin = "9.0.0"
cmake = "3.22.1"
dokka = "2.1.0"
emscripten = "5.0.0"
gradle-pluginPublish = "2.0.0"
jextract = "6-47"
kotlin = "2.3.20-Beta2"
kotlin-wrappers = "2026.1.14"
kotlinx-coroutines = "1.10.2"
sqliteMultipleCiphers = "2.2.7"
turbine = "1.2.1"
undercouch-download = "5.7.0"
vanniktech-mavenPublish = "0.36.0"

[plugins]

conventions-common = { id = "conventions-common", version.ref = "ksqlite" }
conventions-kmp = { id = "conventions-kmp", version.ref = "ksqlite" }
ksqliteCompiler = { id = "ksqlite-compiler", version.ref = "ksqlite" }

android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
android-multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginPublish" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-mavenPublish" }

[libraries]

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlin-wrappers" }
kotlin-js = { module = "org.jetbrains.kotlin-wrappers:kotlin-js", version.ref = "kotlin-wrappers" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
undercouch-dowload = { module = "de.undercouch.download:de.undercouch.download.gradle.plugin", version.ref = "undercouch-download" }
vanniktech-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-mavenPublish" }