# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]

# Project version
ksqlite = "0.0.1"

# Android
android-ndk = "29.0.14206865"
android-sdk-compile = "36"
android-sdk-min = "21"
android-gradlePlugin = "9.2.1"

# Apple
apple-macos-min = "10.13"
apple-ios-min = "12.0"
apple-tvos-min = "12.0"
apple-watchos-min = "5.0"

# Jvm versions
jvm-target-android = "17"
#jvm-target-jvm = "22"
#jvm-toolchain = "22"
jvm-target-jvm = "25"
jvm-toolchain = "25"

androidx-testRunner = "1.7.0"
cmake = "3.22.1"
copyWebpackPlugin = "13.0.1"
dokka = "2.2.0"
gradle-pluginPublish = "2.1.1"
#jextract = "6-47"
jextract = "2-4"
kotlin = "2.4.20-Beta1"
kotlinx-coroutines = "1.11.0"
kotlin-wrappers = "2026.7.1"
sqlite = "3.53.3"
sqliteMultipleCiphers = "2.3.6"
sqliteReleaseYear = "2026"
stately = "2.1.0"
vanniktech-mavenPublish = "0.37.0"

[plugins]

conventions-common = { id = "conventions-common", version.ref = "ksqlite" }
conventions-kmp = { id = "conventions-kmp", version.ref = "ksqlite" }
ksqlite = { id = "ksqlite", version.ref = "ksqlite" }

android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
android-multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginPublish" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-mavenPublish" }

[libraries]

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
androidx-testRunner = { module = "androidx.test:runner", version.ref = "androidx-testRunner" }
copyWebpackPlugin = { module = "npm:copy-webpack-plugin", version.ref = "copyWebpackPlugin" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-wrappers-js = { module = "org.jetbrains.kotlin-wrappers:kotlin-js", version.ref = "kotlin-wrappers" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
stately-concurrentCollections = { module = "co.touchlab:stately-concurrent-collections", version.ref = "stately" }
vanniktech-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-mavenPublish" }